#!/bin/bash
#
# iptables example configuration script
#
# Flush all current rules from iptables
#
iptables -F
#
# Set default policies for INPUT, FORWARD and OUTPUT chains
#
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
#
# Set access for localhost
#
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
#
# Accept to send smtp mail
#
iptables -A OUTPUT -p tcp --dport 25 -j ACCEPT
iptables -A INPUT -p tcp --sport 25 -j ACCEPT
#
# Accept DNS port
#
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -p udp --sport 53 -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p udp --sport 53 -j ACCEPT
#
# Accept packets belonging to established and related connetcions
#
#iptables -A INPUT -p tcp -s 101.201.120.121 --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
#iptables -A OUTPUT -p tcp -d 101.201.120.121 --sport 80 -m state --state ESTABLISHED -j ACCEPT
#iptables -A INPUT -p tcp --dport 443 -j ACCEPT
#iptables -A INPUT -p tcp --sport 443 -j ACCEPT
#iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
#iptables -A OUTPUT -p tcp --sport 443 -j ACCEPT
# Shadowsocks port
iptables -P INPUT DROP
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
#握手成功数据允许通过
iptables -A INPUT -m state --state ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED -j ACCEPT
#开启本地回路
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
#开启PING做检测
#iptables -A INPUT -i eth+ -p icmp --icmp-type 8 -j ACCEPT
#iptables -A OUTPUT -o eth+ -p icmp --icmp-type 0 -j ACCEPT
#开启SSH端口
#iptables -A INPUT -p tcp --dport 22 -j ACCEPT
#iptables -A OUTPUT -p tcp --sport 22 -j ACCEPT
#开启SS代理端口,单个就配置单个，多用户就逗号分隔配置多个
iptables -A INPUT -p tcp -m multiport --destination-port 443 -j ACCEPT
iptables -A OUTPUT -p tcp -m multiport --source-port 443 -j ACCEPT

# Autotrader port
iptables -A INPUT -p tcp --dport 60443 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 60443 -m state --state ESTABLISHED -j ACCEPT
#
# Socket IO port
#
#iptables -A INPUT -p tcp --sport 60080 -j ACCEPT
#iptables -A OUTPUT -p tcp --dport 60080 -j ACCEPT
iptables -A INPUT -p tcp --dport 60080 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 60080 -m state --state ESTABLISHED -j ACCEPT
#
# Save settings
#
/sbin/service iptables save
#
# List rules
#
iptables -L -v
